name = "peakflowstat-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
ENVIRONMENT = "production"
CORS_ORIGIN = "https://peakflowstat.allergyclinic.cc,https://main.peakflowstat.pages.dev"
FRONTEND_URL = "https://peakflowstat.allergyclinic.cc"

[[d1_databases]]
binding = "DB"
database_name = "peakflowstat-db"
database_id = "812f290e-51dc-433b-a2d8-4156dadd72d0"

[[routes]]
pattern = "api.peakflowstat.allergyclinic.cc"
custom_domain = true
